### ISSUE TITLE
Buy sample code and TikTok Api

### ISSUE THREAD

**Issue by BushHess** [jiroawesome/tikapipy#5]
I contact you on discord, twitter, mail did not see you reply. Please contact me again by infor:
Twitter: @BushHess
Discord: HessBush#1958
Mail: [hessbush@gmail.com](mailto:hessbush@gmail.com)

**Comment by jiroawesome** [comment]
Hello, I'm very sorry for the late respond. Friend request has been sent. Please kindly check your Discord. Thanks!

**Comment by xtekky** [comment]
@BushHess He is a skid and a scammer, you can get most of the signatures for free on github

**Comment by jiroawesome** [comment]
@xtekky Bitch he already bought one.  And yes they can. But I made this shit to make it easy. Bro is ruining my career cuz no one's buying his tiktok api shits LMAO

**Comment by jiroawesome** [comment]
@xtekky also gtfo here overpriced seller. Mf just stole an encryption code to public duoyin coders also and selling it for €1500. Clown scammer 😂

**Comment by jiroawesome** [comment]
They can buy mine for only $5. Bitch gtfo here 😂 raiding someone's business cuz of jealousness, LOL! Bitch ass

**Comment by xtekky** [comment]
bro look at u, u just a big skid, I sell for 1.5k because it's things I actually made myself and put the effort into and ppl know that, u earn yo 5 dollars by stealing ppls work and I get 2k in the meantime which still makes me the winner lmfao

**Comment by xtekky** [comment]
Another thing is that you have ladon and not Argus which means that it's completely useless hahaha, big rip off
